### ISSUE TITLE
Can't load my log

### ISSUE THREAD

**Issue by raymanrt** [kcpeppe/regions#9]
Hi, I've replaced the testdata.log with a G1 log produced by my application. The application starts but with an empty canvas. When I press the play button it throws an exception.

Whith your test data the application seems to work correctly.

My G1 conf is as follows:
```
-showversion -XX:+PrintCommandLineFlags
	-XX:+PrintGCDateStamps -XX:+PrintGCDetails
	-XX:+ParallelRefProcEnabled -XX:+PrintReferenceGC
	-XX:+PrintTenuringDistribution -XX:+PrintAdaptiveSizePolicy
	-XX:+DisableExplicitGC -XX:+UseG1GC -XX:MaxGCPauseMillis=250
	-XX:InitiatingHeapOccupancyPercent=45
```
The exception is:
```Exception in thread "Timer-0" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.jclarity.region.model.JavaVirtualMachine.getG1GCHeapAt(JavaVirtualMachine.java:36)
        at com.jclarity.region.model.G1GCHeapView.update(G1GCHeapView.java:63)
        at com.jclarity.region.G1GCHeapAnimation.lambda$start$0(G1GCHeapAnimation.java:36)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.DoublePropertyBase.fireValueChangedEvent(DoublePropertyBase.java:106)
        at javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:113)
        at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:147)
        at com.jclarity.region.FrameCounter.stepForward(FrameCounter.java:34)
        at com.jclarity.region.fx.VideoControls$1.run(VideoControls.java:74)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Exception in thread "Timer-0" java.lang.IllegalStateException: Not on FX application thread; currentThread = Timer-0
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
        at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
        at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
        at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
        at com.sun.javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:575)
        at com.sun.javafx.scene.control.skin.LabeledSkinBase.handleControlPropertyChanged(LabeledSkinBase.java:204)
        at com.sun.javafx.scene.control.skin.ButtonSkin.handleControlPropertyChanged(ButtonSkin.java:71)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase.lambda$registerChangeListener$61(BehaviorSkinBase.java:197)
        at com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler$1.changed(MultiplePropertyChangeListenerHandler.java:55)
        at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
        at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
        at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
        at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
        at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
        at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
        at javafx.scene.control.Labeled.setText(Labeled.java:145)
        at com.jclarity.region.fx.VideoControls$1.run(VideoControls.java:77)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

Thanks,
 Riccardo

**Comment by kcpeppe** [comment]
can you push your data? I don't see the experimental flags being used that would produce this data read by this app
